pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('labs/10-jenkins-intro/starter') {
                    sh 'mvn -B clean package'
                }
                     
            }
        }
        stage('Test') {
            steps {
                dir('labs/10-jenkins-intro/starter') {
                    sh 'mvn -B test'
                }
            }
            post {
                always {
                    dir('labs/10-jenkins-intro/starter') {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                archiveArtifacts artifacts: 'target/site/jacoco/**', fingerprint: false
            }
        }
    }
}
